const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Text,
		C3.Behaviors.Tween,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.Pin,
		C3.Behaviors.Platform,
		C3.Behaviors.Flash,
		C3.Behaviors.Sin,
		C3.Behaviors.bound,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.Mouse,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Keyboard.Cnds.IsLeftRightKeyDown,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.IsCollisionEnabled,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.X,
		C3.Behaviors.Platform.Acts.SetVectorX,
		C3.Behaviors.Platform.Acts.SetJumpStrength,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Platform.Acts.SetAcceleration,
		C3.Behaviors.Platform.Acts.SetCeilingCollision,
		C3.Behaviors.Pin.Cnds.IsPinned,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Acts.SetAngle
	];
};
self.C3_JsPropNameTable = [
	{exitBtnText: 0},
	{gameOverText: 0},
	{restartBtnText: 0},
	{startBtnText: 0},
	{Interpolação: 0},
	{titleText: 0},
	{YouGotIt: 0},
	{arvorePhase2: 0},
	{arvoresPhase1: 0},
	{bordaPonte: 0},
	{CeuEstrelado: 0},
	{ceuPhase3: 0},
	{Sólido: 0},
	{ChaoComFisica: 0},
	{chaoPedra1: 0},
	{chaoTerra: 0},
	{LuaPhase2: 0},
	{luaPhase3: 0},
	{Nuvens: 0},
	{paredeCastelo: 0},
	{Pilar: 0},
	{PlanoDeFundoEmBlocos: 0},
	{PlantasCastelo: 0},
	{ponteCastelo: 0},
	{ponteCastelo2: 0},
	{ponteCastelo3: 0},
	{ponteQuebradaPhase2: 0},
	{ponteTijolo: 0},
	{ceuWin: 0},
	{luaWin: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{ColisionPhase2: 0},
	{ColisionPhase3: 0},
	{Fixar: 0},
	{headWinItem: 0},
	{headWin: 0},
	{colisionHead: 0},
	{exitBtnGO: 0},
	{hitboxv1: 0},
	{restartBtn: 0},
	{startBtn: 0},
	{restartBtnWin: 0},
	{hitBoxV2: 0},
	{changeRightV3: 0},
	{changeLeftV3: 0},
	{changeLeftV2: 0},
	{changeRightV2: 0},
	{vidaV3: 0},
	{moveToRight: 0},
	{moveToLeft: 0},
	{Plataforma: 0},
	{Piscar: 0},
	{Senóide: 0},
	{Sprite: 0},
	{VidaV1: 0},
	{RestritoAoLayout: 0},
	{CentrarEm: 0},
	{Vampire1: 0},
	{LifeV2: 0},
	{Vampire2: 0},
	{Teclado: 0},
	{Áudio: 0},
	{Mouse: 0},
	{Texto: 0},
	{hitboxjump: 0},
	{jumpStrenght: 0}
];

self.InstanceType = {
	exitBtnText: class extends self.ITextInstance {},
	gameOverText: class extends self.ITextInstance {},
	restartBtnText: class extends self.ITextInstance {},
	startBtnText: class extends self.ITextInstance {},
	titleText: class extends self.ITextInstance {},
	YouGotIt: class extends self.ITextInstance {},
	arvorePhase2: class extends self.ITiledBackgroundInstance {},
	arvoresPhase1: class extends self.ITiledBackgroundInstance {},
	bordaPonte: class extends self.ITiledBackgroundInstance {},
	CeuEstrelado: class extends self.ITiledBackgroundInstance {},
	ceuPhase3: class extends self.ITiledBackgroundInstance {},
	ChaoComFisica: class extends self.ITiledBackgroundInstance {},
	chaoPedra1: class extends self.ITiledBackgroundInstance {},
	chaoTerra: class extends self.ITiledBackgroundInstance {},
	LuaPhase2: class extends self.ITiledBackgroundInstance {},
	luaPhase3: class extends self.ITiledBackgroundInstance {},
	Nuvens: class extends self.ITiledBackgroundInstance {},
	paredeCastelo: class extends self.ITiledBackgroundInstance {},
	Pilar: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	PlantasCastelo: class extends self.ITiledBackgroundInstance {},
	ponteCastelo: class extends self.ITiledBackgroundInstance {},
	ponteCastelo2: class extends self.ITiledBackgroundInstance {},
	ponteCastelo3: class extends self.ITiledBackgroundInstance {},
	ponteQuebradaPhase2: class extends self.ITiledBackgroundInstance {},
	ponteTijolo: class extends self.ITiledBackgroundInstance {},
	ceuWin: class extends self.ITiledBackgroundInstance {},
	luaWin: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	ColisionPhase2: class extends self.ISpriteInstance {},
	ColisionPhase3: class extends self.ISpriteInstance {},
	headWinItem: class extends self.ISpriteInstance {},
	headWin: class extends self.ISpriteInstance {},
	colisionHead: class extends self.ISpriteInstance {},
	exitBtnGO: class extends self.ISpriteInstance {},
	hitboxv1: class extends self.ISpriteInstance {},
	restartBtn: class extends self.ISpriteInstance {},
	startBtn: class extends self.ISpriteInstance {},
	restartBtnWin: class extends self.ISpriteInstance {},
	hitBoxV2: class extends self.ISpriteInstance {},
	changeRightV3: class extends self.ISpriteInstance {},
	changeLeftV3: class extends self.ISpriteInstance {},
	changeLeftV2: class extends self.ISpriteInstance {},
	changeRightV2: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Vampire1: class extends self.ISpriteInstance {},
	Vampire2: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Áudio: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Texto: class extends self.ITextInstance {}
}